/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary:           "#A84D48",
        "primary-dk":      "#FF4500",
        surface:           "#f5f0f0",
        "surface-dk":      "#1a1a1b",
        card:              "#ffffff",
        "card-dk":         "rgba(39,39,41,0.92)",
        "card-solid":      "#ffffff",
        "card-solid-dk":   "#272729",
        ink:               "#3d2020",
        "ink-dk":          "#D7DADC",
        subtext:           "#6b6b6b",
        "subtext-dk":      "#B8BABD",
        muted:             "#999",
        "muted-dk":        "#818384",
        border:            "rgba(168,77,72,0.22)",
        "border-dk":       "rgba(52,53,54,0.9)",
        separator:         "rgba(168,77,72,0.15)",
        "separator-dk":    "rgba(52,53,54,0.8)",
        "input-bg":        "#ffffff",
        "input-bg-dk":     "rgba(39,39,41,0.95)",
        "input-border":    "rgba(168,77,72,0.28)",
        "input-border-dk": "rgba(82,83,84,0.8)",
        "tab-bar":         "rgba(255,255,255,0.95)",
        "tab-bar-dk":      "rgba(26,26,27,0.97)",
      },
    },
  },
  plugins: [],
};
